// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACalendar: typeof import('ant-design-vue/es')['Calendar']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    CalendarFilled: typeof import('@ant-design/icons-vue')['CalendarFilled']
    CheckSquareFilled: typeof import('@ant-design/icons-vue')['CheckSquareFilled']
    CountButton: typeof import('./../components/CountButton.vue')['default']
    Counter: typeof import('./../components/Counter.vue')['default']
    DateSelectPopover: typeof import('./../components/date-select-popover/index.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    LogoutOutlined: typeof import('@ant-design/icons-vue')['LogoutOutlined']
    MenuFoldOutlined: typeof import('@ant-design/icons-vue')['MenuFoldOutlined']
    PlusOutlined: typeof import('@ant-design/icons-vue')['PlusOutlined']
    README: typeof import('./../components/README.md')['default']
    SvgIcon: typeof import('./../components/svg-icon/index.vue')['default']
  }
}

export { }
